routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Pengaduan;

Route::get('/', function () {
    $pengaduan = Pengaduan::paginate(5);
    return view('welcome', compact('pengaduan'));
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/pengaduan', 'PengaduanController');
    Route::resource('/petugas', 'PetugasController');
    Route::resource('/masyarakat', 'masyarakatController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/user', 'UserController');
    Route::resource('/response', 'ResponseController');
    
    Route::get('/home', 'HomeController@index')->name('home.index');
    
    Route::get('/pengaduan/trashed', 'PengaduanController@trashed')->name('pengaduan.trashed');
    Route::get('/user-management', 'PetugasController@management_user')->name('petugas.manage');
    Route::get('/pengaduan-detail/', 'PengaduanController@pengaduan_user')->name('pengaduan.pengaduan_user');
    Route::get('user/bot-service', 'UserController@bot_service')->name('user.bot_service');
    Route::get('/detail-user/{id}', 'UserController@index')->name('detail-user.index');
    Route::get('/pengaduan/restore/{id}', 'PengaduanController@restore')->name('pengaduan.restore');
    Route::get('/response-pengaduan/{id}', 'ResponseController@create')->name('response.create');

    
    Route::post('end-response/{id}', 'ResponseController@update');
    Route::post('response/{id}', 'ResponseController@store');
    
    Route::patch('petugas/{id}/{user_id}', 'PetugasController@update');
    Route::patch('user/{id}/{user_id}', 'UserController@update');
    
    Route::delete('/pengaduan/kill/{id}', 'PengaduanController@kill')->name('pengaduan.kill');
});

Route::get('/Detail-pengaduan/{url}', 'PengaduanController@detail')->name('pengaduan.detail');

Auth::routes();

app/Pengaduan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Pengaduan extends Model
{
    use SoftDeletes;
    protected $table = 'pengaduan';
    protected $fillable = [
        'id', 'judul', 'isi_pengaduan', 'gambar', 'url', 'user_id', 'category_id'
    ];
    
    public function users() {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function response()
    {
        return $this->belongsToMany('App\response');
    }
}

app/Http/Controllers/PengaduanController.php
<?php

namespace App\Http\Controllers;

use App\Pengaduan;
use App\Masyarakat;
use App\User;
use App\response;
use App\Category;
use Auth;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PengaduanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengaduan = Pengaduan::orderBy('created_at', 'desc')->whereNotIn('id', DB::table('responses')->pluck('pengaduan_id'))->paginate(5);
        $pengaduan_primary = Pengaduan::where('status', 'proses')->paginate(5);
        $pengaduan_selesai = Pengaduan::where('status', 'selesai')->paginate(5);

        return view('pengaduan.index', compact('pengaduan', 'pengaduan_primary', 'pengaduan_selesai'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::get();
        return view('pengaduan.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request ,[
            'isi_pengaduan' => 'required',
            'category_id' => 'required',
            'gambar' => 'required',
            'url' => 'required'
        ]);
        $user = DB::table('users')->where('id', Auth::id())->first();

        $gambar = $request->gambar;
        $new_gambar = time().$gambar->getClientOriginalName();
        $url = $request->url.'-'.$user->name.'-'.time();
        
        Pengaduan::create([
            'judul' => $request->url,
            'isi_pengaduan' => $request->isi_pengaduan,
            'gambar' => 'public/uploads/pengaduan/'.$new_gambar,
            'url' => Str::slug($url),
            'user_id' => Auth::id(),
            'category_id' => $request->category_id
        ]);
            
        $gambar->move('public/uploads/pengaduan/', $new_gambar);
        return redirect()->route('home.index')->with('success', 'pengaduan berhasil dikirim');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\pengaduan  $pengaduan
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\pengaduan  $pengaduan
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pengaduan = Pengaduan::where('id', $id)->get();
        $category = Category::get();
        return view('pengaduan.edit', compact('pengaduan', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\pengaduan  $pengaduan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pengaduan = Pengaduan::find($id);

        $pengaduan->judul = $request->judul;
        $pengaduan->isi_pengaduan = $request->isi_pengaduan;
        $pengaduan->user_id = Auth::id();
        
        if ($request->has('category_id')) {
            $pengaduan->category_id = $request->category_id;
        }
        if ($request->has('gambar')) {
            $user = DB::table('users')->where('id', Auth::id())->first();

            $gambar = $request->gambar;
            $new_gambar = time().$gambar->getClientOriginalName();
            $url = $request->url.'-'.$user->name.'-'.time();

            $pengaduan->gambar = 'public/uploads/pengaduan/'.$new_gambar;

            $gambar->move('public/uploads/pengaduan/', $new_gambar);
        } 

        $pengaduan->save();

        return redirect()->route('pengaduan.index')->with('success', 'pengaduan berhasil di edit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\pengaduan  $pengaduan
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pengaduan = Pengaduan::findorfail($id);
        $pengaduan->delete();

        return redirect()->back()->with('success', 'pengaduan berhasil dihapus dan masuk kedalam trash');
    }

    public function trashed()
    {
        $pengaduan = Pengaduan::onlyTrashed()->paginate(2);
        return view('pengaduan.trash', compact('pengaduan'));
    }

    public function restore($id)
    {
        $pengaduan = Pengaduan::withTrashed()->where('id', $id)->first();
        $pengaduan->restore();

        return redirect()->back()->with('success', 'pengaduan berhasil direstore');
    }

    public function kill($id)
    {
        $pengaduan = Pengaduan::withTrashed()->where('id', $id)->first();
        $pengaduan->forceDelete();
        Storage::delete(['file', $pengaduan->gambar]);

        return redirect()->back()->with('success', 'pengaduan berhasil dihapus');
    }

    public function detail($url) {
        $data = Pengaduan::where('url', $url)->get();
        
        return view('pengaduan.detail', compact('data'));
    }

    public function pengaduan_user()
    {
        $pengaduan = Pengaduan::orderBy('created_at', 'desc')->where('user_id', Auth::id())->get();
        return view('pengaduan.pengaduan_user', compact('pengaduan'));
    }
}

resources/views/pengaduan/create.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>tambah data</h3>
    @endsection
    @section('content')

        <form action=" {{ route('pengaduan.store') }} " method="post" enctype="multipart/form-data">
        @csrf
            <div class="form-group">
                <label for="judul_pengaduan">Judul pengaduan</label>
                <input type="text" class="form-control" name="url" id="judul_pengaduan" placeholder="Contoh : Tanah longsor di daerah pancoran mas">
                <small id="emailHelp" class="form-text text-muted">Judul harus sama dengan apa yang ingin anda adukan!</small>
            </div>

            <div class="form-group">
                <label for="pengaduan">Tulis pengaduan disini</label>
                <textarea name="isi_pengaduan" class="form-control" id="pengaduan" rows="3"></textarea>
            </div>
            <div class="section-title">Category</div>
            <div class="form-group">
                <select class="form-control select2" name="category_id">
                    <option value="" disabled selected>-- pilih category --</option>
                    @foreach($category as $categor)
                        <option value=" {{ $categor->id }} "> {{ $categor->name }} </option>
                    @endforeach

                </select>
            </div>
            <div class="section-title">Gambar</div>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile" name="gambar">
                <label class="custom-file-label" for="customFile">pilih gambar</label>
            </div>

            
            <button type="submit" class="btn btn-primary mt-5">Tambah data</button>

        </form>

    @endsection('content')

resources/views/pengaduan/detail.blade.php
@extends('home_layouts.index')

    @section('content')

        @foreach($data as $pengaduan)
            <div class="container">
                <div class="row row-margin-up">
                    <div class="col-md-4">
                        <img class="img-thumbnail" src=" {{ asset($pengaduan->gambar) }} ">
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <h4 class="pt-5">Pengirim : {{ $pengaduan->users->name }}</h4>
                            </div>
                            <div class="col-md-12">
                                <h4 class="">status pengaduan : {{ $pengaduan->status }}</h4>
                            </div>
                            <div class="col-md-12">
                                <h4 class="">waktu : {{ $pengaduan->created_at }}</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-12">
                                <h1>{{ $pengaduan->judul }}</h1>
                            </div>
                            <div class="col-md-6">
                                <p> {{ $pengaduan->isi_pengaduan }} </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        @endforeach

    @endsection('content')

resources/views/pengaduan/edit.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>tambah data</h3>
    @endsection
    @section('content')

        @foreach($pengaduan as $pengadu)
        <form action=" {{ route('pengaduan.update', $pengadu->id) }} " method="post" enctype="multipart/form-data">
        @csrf
        @method('patch')
            <div class="form-group">
                <label for="judul_pengaduan">Judul pengaduan</label>
                <input type="tetx" class="form-control" name="judul" id="judul_pengaduan" value=" {{ $pengadu->judul }} ">
            </div>

            <div class="form-group">
                <label for="pengaduan">Tulis pengaduan disini</label>
                <textarea name="isi_pengaduan" class="form-control" id="pengaduan" rows="3" value=" {{ $pengadu->isi_pengaduan }} "></textarea>
            </div>
            <div class="section-title">Category</div>
            <div class="form-group">
                <select class="form-control select2" name="category_id">
                    <option value="" disabled selected>-- pilih category --</option>
                    @foreach($category as $categor)
                        <option value=" {{ $categor->id }} "> {{ $categor->name }} </option>
                    @endforeach

                </select>
            </div>
            <div class="section-title">Gambar</div>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile" name="gambar">
                <label class="custom-file-label" for="customFile">pilih gambar</label>
            </div>

            
            <button type="submit" class="btn btn-primary mt-5">Edit data</button>

        </form>
        @endforeach

    @endsection('content')

resources/views/pengaduan/index.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>Pengaduan</h3>
    @endsection

    @section('content')
    @if(Session::has('success'))
        <script>
            $('.success', function() {
                swal('', " {{ Session('success') }} ", 'success', {
                    buttons: false,
                    timer: 3000,
                });
            });
        </script>
        <div class="success"></div>
    @endif
    
        <div class="row">
            <div class="section-title">Pengaduan terbaru</div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>category</th>
                        <th>tanggal</th>
                        <th>Judul aduan</th>
                        <th>status</th>
                        <th>Gambar</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($pengaduan as $pengadua => $pengadu)
                    <tr>
                        <th scope="row">{{ $loop->index + 1 }}</th>
                        <td> {{ $pengadu->users['name'] }} </td>
                        <td> {{ $pengadu->category['name'] }} </td>
                        <td> {{ $pengadu->created_at }} </td>
                        <td> {{ $pengadu->judul }} </td>
                        <td> {{ $pengadu->status }} </td>
                        <td><img class="img-thumbnail" src="{{ asset($pengadu->gambar) }}" width="100"></td>
                        <td>
                            <form action=" {{ route('pengaduan.destroy', $pengadu->id) }} " method="post">
                                @csrf 
                                @method('delete')
                                <div class="row">

                                    <div class="col-md-4">
                                        <a href=" {{ url('Detail-pengaduan', $pengadu->url) }} " class="btn btn-info" data-toggle="tooltip" data-original-title="Detail"> <i class="icon-profile"></i> </a>
                                    </div>
                                    <div class="col-md-4">
                                        <a href=" {{ url('response-pengaduan', $pengadu->id) }} " class="btn  btn-success" data-toggle="tooltip" data-original-title="response"> <i class="icon-redo2"></i> </a>
                                    </div>
                                    <div class="col-md-4">
                                        <button type="submit" class="btn  btn-danger buttons" data-toggle="tooltip" data-original-title="Delete"> <i class="icon-cross"></i> </button>
                                    </div>
                                </div>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="col-md-12">

                <div class="row mt-2">
                    <div class="col-md-10">
                        {{ $pengaduan->links() }}
                    </div>
                    <div class="col-md-2">
                        <a href=" {{ route('pengaduan.create') }}  " class="btn btn-primary">Tambah Data</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="section-title">Pengaduan dalam proses</div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>tanggal</th>
                        <th>Judul aduan</th>
                        <th>status</th>
                        <th>Gambar</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($pengaduan_primary as $pengaduap => $pengadup)
                    <tr>
                        <th scope="row">{{ $pengaduap + $pengaduan_primary->firstitem() }}</th>
                        <td> {{ $pengadup->users->name }} </td>
                        <td> {{ $pengadup->created_at }} </td>
                        <td> {{ $pengadup->judul }} </td>
                        <td> {{ $pengadup->status }} </td>
                        <td><img class="img-thumbnail" src="{{ asset($pengadup->gambar) }}" width="100"></td>
                        <td>
                            <div class="row">
                                <form action=" {{ url('end-response', $pengadup->id) }} " method="post">
                                    @csrf
                                    <div class="col-md-4">
                                        <a href=" {{ url('Detail-pengaduan', $pengadup->url) }} " class="btn btn-info" data-toggle="tooltip" data-original-title="Detail"> <i class="icon-profile"></i> </a>
                                    </div>
                                    <div class="col-md-4">
                                        <button type="submit" class="btn  btn-success buttons" data-toggle="tooltip" data-original-title="Tandai selesai"> <i class="icon-checkmark2"></i> </button>
                                    </div>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="row mt-2">
                <div class="col-md-10">
                {{ $pengaduan->links() }}
                </div>
            </div>
                        
        </div>


        <div class="row">
            <div class="section-title">Pengaduan yang sudah selesai</div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>tanggal</th>
                        <th>Judul aduan</th>
                        <th>status</th>
                        <th>Gambar</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($pengaduan_selesai as $pengadus => $pengads)
                    <tr>
                        <th scope="row">{{ $pengadus + $pengaduan_selesai->firstitem() }}</th>
                        <td> {{ $pengads->users->name }} </td>
                        <td> {{ $pengads->created_at }} </td>
                        <td> {{ $pengads->judul }} </td>
                        <td> {{ $pengads->status }} </td>
                        <td><img class="img-thumbnail" src="{{ asset($pengads->gambar) }}" width="100"></td>
                        <td>
                            <div class="row">
                                <div class="col-md-4">
                                    <a href=" {{ url('Detail-pengaduan', $pengads->url) }} " class="btn btn-info" data-toggle="tooltip" data-original-title="Detail"> <i class="icon-profile"></i> </a>
                                </div>
                                <div class="col-md-4">
                                    <form action=" {{ route('pengaduan.destroy', $pengads->id) }} " method="post">
                                        @csrf 
                                        @method('delete')
                                        <button type="submit" class="btn  btn-danger buttons" data-toggle="tooltip" data-original-title="Delete"> <i class="icon-cross"></i> </button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="row mt-2">
                <div class="col-md-10">
                {{ $pengaduan->links() }}
                </div>
            </div>
        </div>


    @endsection('content')

resources/views/pengaduan/pengaduan_user.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>Pengaduan saya</h3>
    @endsection

    @section('content')
        
        <div class="row">
            @foreach($pengaduan as $pengadu)
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h2> {{ $loop->index + 1 }}. {{ $pengadu->judul }}</h2>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <img src=" {{ $pengadu->gambar }} " class="img-thumbnail" width="300">
                            </div>
                            <div class="col-md-6">
                                <h5> {{ $pengadu->judul }} </h5>
                                <p> {{ $pengadu->isi_pengaduan }} </p>
                                <p> Status : <i> {{ $pengadu->status }} </i></p>
                                <p> {{ $pengadu->status }} </p>
                                <a href=" {{ route('pengaduan.edit', $pengadu->id) }} " class="btn btn-warning" data-toggle="tooltip" data-original-title="Edit"> <i class="icon-pen"></i> Edit pengaduan </a>
                            </div> 
                        </div>
                    </div>
                </div>
            </div>
            @endforeach
        </div>

        <div class="row">
            <div class="col-md-6">
                <h1>Terima kasih telah melaporkan aduanmu!</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora, officia aut iure officiis deleniti possimus veniam rerum quidem quae eaque minus cumque quaerat aliquid impedit enim facilis quos, omnis voluptates?</p>
            </div>
            <div class="col-md-6">
                <img src=" {{ asset('assets/img/undraw_super_thank_you_obwk.svg') }} " width="400">
            </div> 
        </div>

    @endsection('content')

resources/views/pengaduan/trash.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>Trash</h3>
    @endsection
    @section('content')

    @if(Session::has('success'))
        <script>
            $('.success', function() {
                swal('', " {{ Session('success') }} ", 'success', {
                    buttons: false,
                    timer: 3000,
                });
            });
        </script>
        <div class="success"></div>
    @endif
        <div class="row">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>tanggal</th>
                        <th>Judul aduan</th>
                        <th>Gambar</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($pengaduan as $pengadua => $pengadu)
                    <tr>
                        <th scope="row">{{ $pengadua + $pengaduan->firstitem() }}</th>
                        <td> {{ $pengadu->users->name }} </td>
                        <td> {{ $pengadu->created_at }} </td>
                        <td> {{ $pengadu->url }} </td>
                        <td><img class="img-thumbnail" src="{{ asset($pengadu->gambar) }}" width="100"></td>
                        <td>
                            <form action="{{ route('pengaduan.kill', $pengadu->id) }}" method="post">
                                @csrf 
                                @method('delete')
                                <div class="row">
                                    <div class="col-md-6">
                                        <a href=" {{ route('pengaduan.restore', $pengadu->id) }} " class="btn btn-primary">Restore</a>
                                    </div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-danger buttons">delete</button>
                                    </div>
                                </div>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="row mt-2">
                <div class="col-md-10">
                {{ $pengaduan->links() }}
                </div>
            </div>          
        </div>

    @endsection