routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Pengaduan;

Route::get('/', function () {
    $pengaduan = Pengaduan::paginate(5);
    return view('welcome', compact('pengaduan'));
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/pengaduan', 'PengaduanController');
    Route::resource('/petugas', 'PetugasController');
    Route::resource('/masyarakat', 'masyarakatController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/user', 'UserController');
    Route::resource('/response', 'ResponseController');
    
    Route::get('/home', 'HomeController@index')->name('home.index');
    
    Route::get('/pengaduan/trashed', 'PengaduanController@trashed')->name('pengaduan.trashed');
    Route::get('/user-management', 'PetugasController@management_user')->name('petugas.manage');
    Route::get('/pengaduan-detail/', 'PengaduanController@pengaduan_user')->name('pengaduan.pengaduan_user');
    Route::get('user/bot-service', 'UserController@bot_service')->name('user.bot_service');
    Route::get('/detail-user/{id}', 'UserController@index')->name('detail-user.index');
    Route::get('/pengaduan/restore/{id}', 'PengaduanController@restore')->name('pengaduan.restore');
    Route::get('/response-pengaduan/{id}', 'ResponseController@create')->name('response.create');

    
    Route::post('end-response/{id}', 'ResponseController@update');
    Route::post('response/{id}', 'ResponseController@store');
    
    Route::patch('petugas/{id}/{user_id}', 'PetugasController@update');
    Route::patch('user/{id}/{user_id}', 'UserController@update');
    
    Route::delete('/pengaduan/kill/{id}', 'PengaduanController@kill')->name('pengaduan.kill');
});

Route::get('/Detail-pengaduan/{url}', 'PengaduanController@detail')->name('pengaduan.detail');

Auth::routes();

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'id', 'name', 'user_id'
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::paginate(5);
        return view('category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:categories'
        ]);

        Category::create([
            'name' => $request->name,
            'user_id' => Auth::id()
        ]);

        return redirect()->route('category.index')->with('success', 'category berhasil di tambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::where('id', $id)->get();
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $category->name = $request->name;
        $category->user_id = Auth::id();

        $category->save();

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/category/create.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>Tambah Data</h3>
    @endsection

    @section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form class="needs-validation" novalidate="" action=" {{ route('category.store') }} " method="post">
                    @csrf
                        <div class="section-title">Category name</div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="name">
                            <div class="invalid-feedback">
                                This column is required!
                            </div>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
        
    </div>
    
    @endsection

resources/views/category/edit.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>Edit Data</h3>
    @endsection

    @section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    @foreach($category as $categ)
                    <form class="needs-validation" novalidate="" action=" {{ route('category.update', $categ->id) }} " method="post">
                    @csrf
                    @method('patch')
                        <div class="section-title">Category name</div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="name" value=" {{ $categ->name }} ">
                            <div class="invalid-feedback"> 
                                This column is required!
                            </div>
                        </div>
                        
                        <div class="text-right">
                            <button class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                    @endforeach
                </div>
            </div>
            
        </div>
        
    </div>
    
    @endsection

resources/views/category/index.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>Category</h3>
    @endsection

    @section('content')
    @if(Session::has('success'))
        <script>
            $('.success', function() {
                swal('', " {{ Session('success') }} ", 'success', {
                    buttons: false,
                    timer: 3000,
                });
            });
        </script>
        <div class="success"></div>
    @endif
    
        <div class="row">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($category as $categor => $categ)
                    <tr>
                        <th scope="row">{{ $loop->index + 1 }}</th>
                        <td> {{ $categ->name }} </td>
                        <td width="20%">
                            <div class="col-md-12">
                            
                                <form action=" {{ route('category.destroy', $categ->id) }} " method="post">
                                    @csrf 
                                    @method('delete')
                                    <div class="row">
                                    <div class="col-md-4">
                                        <a href=" {{ route('category.edit', $categ->id) }} " class="btn btn-warning" data-toggle="tooltip" data-original-title="Edit"> <i class="icon-pen"></i> </a>
                                    </div>
                                    <div class="col-md-4">
                                        <button type="submit" class="btn  btn-danger buttons" data-toggle="tooltip" data-original-title="Delete"> <i class="icon-cross"></i> </button>
                                    </div>
                                    </div>
                                </form>
                            
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="row mt-2">
                <div class="col-md-10">
                    {{ $category->links() }}
                </div>
                <div class="col-md-2">
                    <a href=" {{ route('category.create') }}  " class="btn btn-primary">Tambah Data</a>
                </div>
            </div>
        </div>


    @endsection('content')