routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Pengaduan;

Route::get('/', function () {
    $pengaduan = Pengaduan::paginate(5);
    return view('welcome', compact('pengaduan'));
});

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/pengaduan', 'PengaduanController');
    Route::resource('/petugas', 'PetugasController');
    Route::resource('/masyarakat', 'masyarakatController');
    Route::resource('/category', 'CategoryController');
    Route::resource('/user', 'UserController');
    Route::resource('/response', 'ResponseController');
    
    Route::get('/home', 'HomeController@index')->name('home.index');
    
    Route::get('/pengaduan/trashed', 'PengaduanController@trashed')->name('pengaduan.trashed');
    Route::get('/user-management', 'PetugasController@management_user')->name('petugas.manage');
    Route::get('/pengaduan-detail/', 'PengaduanController@pengaduan_user')->name('pengaduan.pengaduan_user');
    Route::get('user/bot-service', 'UserController@bot_service')->name('user.bot_service');
    Route::get('/detail-user/{id}', 'UserController@index')->name('detail-user.index');
    Route::get('/pengaduan/restore/{id}', 'PengaduanController@restore')->name('pengaduan.restore');
    Route::get('/response-pengaduan/{id}', 'ResponseController@create')->name('response.create');

    
    Route::post('end-response/{id}', 'ResponseController@update');
    Route::post('response/{id}', 'ResponseController@store');
    
    Route::patch('petugas/{id}/{user_id}', 'PetugasController@update');
    Route::patch('user/{id}/{user_id}', 'UserController@update');
    
    Route::delete('/pengaduan/kill/{id}', 'PengaduanController@kill')->name('pengaduan.kill');
});

Route::get('/Detail-pengaduan/{url}', 'PengaduanController@detail')->name('pengaduan.detail');

Auth::routes();

app/Petugas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Petugas extends Model
{
    protected $table = 'Petugas';
    protected $fillable = [
        'id', 'nama_petugas', 'email', 'password', 'telp', 'user_id'
    ];

    public function users()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PetugasController.php
<?php

namespace App\Http\Controllers;

use App\Petugas;
use App\User;
use App\Masyarakat;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class PetugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('petugas.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('petugas.create');
    }

    public function management_user()
    {
        $masyarakat = Masyarakat::paginate(5);
        $petugas = Petugas::paginate(5);
        return view('petugas.management_user', compact('petugas', 'masyarakat'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_petugas' => 'required',
            'email' => 'required|unique:users',
            'password' => 'required',
            'telp' => 'required',
            'level' => 'required'
        ]);

        $user = User::create([
            'name' => $request->nama_petugas,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'level' => $request->level
        ]);

        $petugas = Petugas::create([
            'nama_petugas' => $request->nama_petugas,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'telp' => $request->telp,
            'level' => $request->level,
            'user_id' => $user->id
        ]);
        
        return redirect()->route('petugas.management_user')->with('done', 'Data berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $petugas = Petugas::where('id', $id)->get();
        return view('petugas.edit', compact('petugas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id, $user_id)
    {
        $petugas = Petugas::find($id);
        $user = User::find($user_id);

        $user->name = $request->nama_petugas;
        $user->email = $request->email;
        $user->level = $request->level;
        $user->password = Hash::make($request->password);

        $petugas->nama_petugas = $request->nama_petugas;
        $petugas->email = $request->email;
        $petugas->level = $request->level;
        $petugas->telp = $request->telp;
        $petugas->password = Hash::make($request->password);

        $petugas->save();
        $user->save();

        return redirect()->route('petugas.management_user')->with('done', 'data berhasil di edit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $user = User::findorfail($id);
        $petugas = Petugas::where('user_id', $user->id);
        $petugas->delete();
        $user->delete();
        
        return redirect()->route('petugas.management_user')->with('done', 'data berhasil di hapus');
    }
}

resources/views/petugas/create.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>tambah data</h3>
    @endsection
    
    @section('content')

            <form action=" {{ route('petugas.store') }} " method="post">
            @csrf
                <div class="form-group row">
                    <label for="nama_petugas" class="col-md-4 col-form-label text-md-right">{{ __('nama petugas') }}</label>

                    <div class="col-md-6">
                        <input id="nama_petugas" type="text" class="form-control @error('nama_petugas') is-invalid @enderror" name="nama_petugas" value="{{ old('nama_petugas') }}" required autocomplete="nama_petugas" autofocus>

                        @error('nama_petugas')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('email') }}</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __(' password ') }}</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" value="{{ old('password') }}" required autocomplete="password" autofocus>

                        @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="telp" class="col-md-4 col-form-label text-md-right">{{ __('no telephone') }}</label>

                    <div class="col-md-6">
                        <input id="telp" type="number" class="form-control @error('telp') is-invalid @enderror" name="telp" value="{{ old('telp') }}" required autocomplete="telp" autofocus>

                        @error('telp')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="level" class="col-md-4 col-form-label text-md-right">{{ __('Level') }}</label>

                    <div class="col-md-6">
                        <select class="form-control" name="level">
                            <option>-- Pilih Level user --</option>
                            <option value="admin" > Admin </option>
                            <option value="petugas" > petugas </option>
                        </select>

                        @error('level')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10"></div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary">Tambah data</button>
                    </div>
                </div>

            </form>

    @endsection('content')

resources/views/petugas/edit.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>tambah data</h3>
    @endsection
    
    @section('content')

            @foreach($petugas as $petu)
            <form action=" {{ url('petugas/' . $petu->id . '/' . $petu->user_id) }} " method="post">
            @csrf
            @method('patch')
                <div class="form-group row">
                    <label for="nama_petugas" class="col-md-4 col-form-label text-md-right">{{ __('nama petugas') }}</label>

                    <div class="col-md-6">
                        <input id="nama_petugas" type="text" class="form-control @error('nama_petugas') is-invalid @enderror" name="nama_petugas" value="{{ $petu->nama_petugas }}" autocomplete="nama_petugas" autofocus>

                        @error('nama_petugas')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('email') }}</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $petu->email }}" autocomplete="email" autofocus>

                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __(' password ') }}</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" value="{{ old('password') }}" required autocomplete="password" autofocus>

                        @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="telp" class="col-md-4 col-form-label text-md-right">{{ __('no telephone') }}</label>

                    <div class="col-md-6">
                        <input id="telp" type="number" class="form-control @error('telp') is-invalid @enderror" name="telp" value="{{ $petu->telp }}" autocomplete="telp" autofocus>

                        @error('telp')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

                <div class="form-group row">
                    <label for="level" class="col-md-4 col-form-label text-md-right">{{ __('Level') }}</label>

                    <div class="col-md-6">
                        <select class="form-control" name="level">
                            <option value="admin" @if($petu->level = "Admin") {{ 'selected' }} @endif> Admin </option>
                            <option value="petugas" @if($petu->level = "petugas") {{ 'selected' }} @endif> petugas </option>
                        </select>

                        @error('level')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10"></div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary">Edit data</button>
                    </div>
                </div>
            </form>
            @endforeach

    @endsection('content')

resources/views/petugas/index.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
      <h3>Petugas</h3>
    @endsection
    @section('content')
    
    <div class="row">
    <h5>Pengaduan Terbaru</h5>
      <div class="col-md-12">
        <div class="col-md-6">
        
        </div>
      </div>
    </div>

    <div class="row">
    <h5>Pengaduan yang harus dikerjakan terlebih dahulu</h5>
      <div class="col-md-12">
        <div class="col-md-6">
        
        </div>
      </div>
    </div>

    @endsection('content')

resources/views/petugas/management_user.blade.php
@extends('dashboard_layout.Home')
    @section('content-header')
        <h3>Daftar user</h3>
    @endsection
    @section('content')

        @if(Session::has('done'))
            <script>
                $('.success', function() {
                    swal('', " {{ Session('success') }} ", 'success', {
                        buttons: false,
                        timer: 2000,
                    });
                });
            </script>
            <div class="success"></div>
        @endif
    
        <div class="row">
            <div class="section-title">Petugas</div>
            <table class="table table-hover" id="table-1">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>Email</th>
                        <th>No telephone</th>
                        <th>level</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($petugas as $petuga => $petu)
                    <tr>
                        <th scope="row">{{ $petuga + $petugas->firstitem() }}</th>
                        <td> {{ $petu->nama_petugas }} </td>
                        <td> {{ $petu->email }} </td>
                        <td> {{ $petu->telp }} </td>
                        <td> {{ $petu->level }} </td>
                        <td width="20%">
                            <div class="col-md-12">
                                <form action=" {{ route('petugas.destroy', $petu->id) }} " method="post">
                                    @csrf 
                                    @method('delete')
                                    <div class="row">
                                        <div class="col-md-6">
                                            <a href=" {{ route('petugas.edit', $petu->id) }} " class="btn btn-warning"> edit </a>
                                        </div> 
                                        <div class="col-md-6">
                                            <button type="submit" class="btn btn-danger buttons">delete</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="row mt-2">
                <div class="col-md-10">
                    {{ $petugas->links() }}
                </div>
                <div class="col-md-2">
                    <a href=" {{ route('petugas.create') }}  " class="btn btn-primary">Tambah Data</a>
                </div>
            </div>

        </div>
        
        <div class="row mt-3">
            <div class="section-title">Masyarakat</div>
            <table class="table table-hover" id="table-2">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama</th>
                        <th>NIK</th>
                        <th>No telephone</th>
                        <th>Alamat</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($masyarakat as $masya => $msy)
                    <tr>
                        <th scope="row">{{ $masya + $masyarakat->firstitem() }}</th>
                        <td> {{ $msy->name }} </td>
                        <td> {{ $msy->NIK }} </td>
                        <td> {{ $msy->telp }} </td>
                        <td> {{ $msy->alamat }} </td>
                        <td width="20%">
                            <div class="row">
                                <form action=" {{ route('masyarakat.destroy', $msy->id) }} " method="post">
                                    @csrf 
                                    @method('delete')
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-danger buttons">delete</button>
                                    </div>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="row mt-2">
                <div class="col-md-10">
                {{ $masyarakat->links() }}
                </div>
                <div class="col-md-2">
                    <a href=" {{ route('masyarakat.create') }}  " class="btn btn-primary">Tambah Data</a>
                </div>
            </div>

        </div>

    @endsection('content')